### ISSUE TITLE
Package not importable due to missing dist directory

### ISSUE THREAD

**Issue by mogelbrod** [taehwanno/is-react-synthetic-event#7]
[package.json points to `dist/index.*`](https://github.com/taehwanno/is-react-synthetic-event/blob/a20a6415f22309b3c6142def792069c9d750fcee/package.json#L4-L6), but none of the files exist in the published package as of v1.1.

Workaround is to import it via
```js
import isReactSyntheticEvent from 'is-react-synthetic-event/src/index'
```

**Comment by taehwanno** [comment]
I republished the package as v1.1.1. Thanks for reporting 😅
